name: javafx-xdg-open-snap
version: '0.1.0'
summary: A test for opening browser in a snap using JavaFX
description: https://bugs.launchpad.net/snapd/+bug/1831992

grade: stable
confinement: strict
base: core18

parts:
  javafx-xdg-open-snap:
    plugin: maven
    source: https://github.com/astonbitecode/javafx-xdg-open-snap.git
    override-build: |
      mvn clean install
    build-packages:
      - openjdk-11-jdk
      - maven
    stage-packages:
      - openjdk-11-jdk
      - maven
    organize:
      ../build/target: opt/javafx-xdg-open-snap/target
  gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
  env:
    plugin: nil
    after:
      - javafx-xdg-open-snap
      - gtk3
apps:
  javafx-xdg-open-snap:
    command: java --module-path $TARGET_PATH/lib --add-modules javafx.base,javafx.controls,javafx.graphics -Duser.home=${HOME} -jar $TARGET_PATH/javafx-xdg-open-snap-0.1.0-SNAPSHOT.jar
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - opengl
      - network
      - wayland
    environment:
      JAVA_HOME: ${SNAP}/usr/lib/jvm/java-11-openjdk-${SNAP_ARCH}
      TARGET_PATH: ${SNAP}/opt/javafx-xdg-open-snap/target
      PATH: ${JAVA_HOME}/bin:${PATH}
